spring.application.name=account-service

spring.datasource.url=jdbc:mysql://localhost:3306/treasure_db
spring.datasource.username=treasure_user
spring.datasource.password=treasure_pass
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration